[package]
name = "modula_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.30"
wgpu = "0.20"
env_logger = "0.11"
pollster = "0.3"
log = "0.4"
bevy_ecs = "0.13"