[package]
name = "modula_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.14"
bevy_ecs = "0.13"
modula_core ={ path = "../modula_core" }
winit = "0.30"
